### ISSUE TITLE
Issues: Main.java

### ISSUE THREAD

**Issue by jazzie-b** [pyroib/ITC205-G7#28]
**Filename:** Main.java
**Document Changes
Whole Page:** 
- Method ordering incorrect based on modifiers, see 4.8.7 in style guide
- Incorrect indentation, tabs used instead of 4 spaces, see code style guide pdf

**Lines:** 34, 45, 53, 55, 57, 61, **66, 70, 74, 78, 82 ,86, 90, 94, 98, 102, 106,** 111, 179, 203, 207 
**(Optional) Change:**  Unnecessary vertical white spacing, neither discouraged or encouraged, see 4.6.1. However, in the case of main method (bolder lines numbers) additional white lines between each case statement make it difficult to read.

**Line:** 175, 178, 200
**Change:** Method with in method call, see style guide pdf

**Comment by pyroib** [comment]
These should be address in merge - https://github.com/pyroib/ITC205-G7/tree/MerajFinalReview
