### ISSUE TITLE
Issues: Loan.java

### ISSUE THREAD

**Issue by jazzie-b** [pyroib/ITC205-G7#29]
**Filename:** Loan.java
**Document Changes
Whole Page:** 
- Incorrect indentation, tabs used instead of 4 spaces, see code style guide pdf

**Line:** 8
**(Possible) Change:** enum formatting needs to be consistent between each author, will 
discuss how this needs to be formatted and if this needs to be changed.

**Line:** 30, 31
**Change:** No indentation on block statement, need to be 4 spaces. See code style guide pdf.

**Line:** 51, 79, 84
**Change:**  Meaningful method names, see code style guide pdf

**Line:** 79, 84
**Change:** Method name don’t follow method naming conventions, see style guide pdf

**Comment by pyroib** [comment]
These should be address in merge - https://github.com/pyroib/ITC205-G7/tree/MerajFinalReview
