### ISSUE TITLE
Issues: PayFineControl.java

### ISSUE THREAD

**Issue by jazzie-b** [pyroib/ITC205-G7#31]
**Filename:** PayFineControl.java
**Document Changes**
**Whole Page:** 
- Incorrect indentation, tabs used instead of 4 spaces, see code style guide pdf
- Incorrect spacing between methods, should be 2 lines not 1

**Line:** 5-7
**(Possible) Change:** enum formatting needs to be consistent between each author, will discuss how this needs to be formatted and if this needs to be changed.

**Line:** 5-11 
**Change:** Group variables together based on modifier, see 4.8.7 in style guide

**Line:** 9
**Change:** Meaningful variable names, see code style guide pdf

**Line:** 34
**(Optional) Change:**  Unnecessary vertical white spacing, neither discouraged or encouraged, see 4.6.1.

**Line:** 57, 59
**Change:** Method with in method call, see style guide pdf

**Comment by pyroib** [comment]
These should be address in merge - https://github.com/pyroib/ITC205-G7/tree/MerajFinalReview
