### ISSUE TITLE
Issues: FixBookUi.java

### ISSUE THREAD

**Issue by jazzie-b** [pyroib/ITC205-G7#32]
**Filename:** FixBookUi.java
**Document Changes
Whole Page:** 
- Incorrect indentation, tabs used instead of 4 spaces, see code style guide pdf
- Incorrect spacing between methods, should be 2 lines not 1

**Line:** 5-7
**(Possible) Change:** enum formatting needs to be consistent between each author, will discuss how this needs to be formatted and if this needs to be changed.

**Line:** 9, 10, 11
**Change:** Meaningful variable names, see code style guide pdf

**Line:** 20, 24, 74
**Change:** Meaningful method names, see code style guide pdf

**Lines:** 26, 30, 44, 53, 57 
**(Optional) Change:**  Unnecessary vertical white spacing, neither discouraged or encouraged, see 4.6.1. However, in the run method (bolded lines numbers) additional white lines between each case statement make it difficult to read.

**Line:** 48
**Change:** Method with in method call, see style guide pdf

**Comment by TwistedHead** [comment]
Line: 20, 24, 74
Change: Meaningful method names, see code style guide pdf
- These method names are consistent with ReturnBookUi, BorrowBookUi and PayFineUi. 

Line: 9, 10, 11
Change: Meaningful variable names, see code style guide pdf
- Updated as requested

Lines: 26, 30, 44, 53, 57
(Optional) Change: Unnecessary vertical white spacing, neither discouraged or encouraged, see 4.6.1. However, in the run method (bolded lines numbers) additional white lines between each case statement make it difficult to read.
- Removed Vertical White spacing

**Comment by pyroib** [comment]
These should be address in merge - https://github.com/pyroib/ITC205-G7/tree/MerajFinalReview
