### ISSUE TITLE
Issues: FixBookControl.java

### ISSUE THREAD

**Issue by jazzie-b** [pyroib/ITC205-G7#33]
**Filename:** FixBookControl.java
**Document Changes
Whole Page:** 
- Incorrect indentation, tabs used instead of 4 spaces, see code style guide pdf
- Incorrect spacing between methods, should be 2 lines not 1

**Line:** 3 -12 
**Change:** Group variables together based on modifier, see 4.8.7 in style guide

**Line:** 5-7
**(Possible) Change:** enum formatting needs to be consistent between each author, will discuss how this needs to be formatted and if this needs to be changed.

**Line:** 9 
**Change:**  state could be more meaningful variable names, see code style guide pdf

**Line:** 42
**Change:** Method with in method call, see style guide pdf

**Comment by pyroib** [comment]
These should be address in merge - https://github.com/pyroib/ITC205-G7/tree/MerajFinalReview

**Comment by jazzie-b** [comment]
Realised reviewing error on line 42 is actually line 52.
